In [6]:
import pandas as pd
import yfinance as yf
import pandas_ta as ta

In [8]:


df = pd.DataFrame()
df = df.ta.ticker('AAPL', period='5y')
df.ta.log_return(cumulative=True, append=True)

Date
2018-04-02 00:00:00-04:00    0.000000
2018-04-03 00:00:00-04:00    0.010207
2018-04-04 00:00:00-04:00    0.029149
2018-04-05 00:00:00-04:00    0.036059
2018-04-06 00:00:00-04:00    0.010148
                               ...
2023-03-23 00:00:00-04:00    1.386486
2023-03-24 00:00:00-04:00    1.394757
2023-03-27 00:00:00-04:00    1.382388
2023-03-28 00:00:00-04:00    1.378399
2023-03-29 00:00:00-04:00    1.397997
Name: CUMLOGRET_1, Length: 1258, dtype: float64

In [ ]:
df.ta.indicators()

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods

In [ ]:
ind_list = df.ta.indicators()

Pandas TA - Technical Analysis Indicators - v0.3.14b0
Total Indicators & Utilities: 205
Abbreviations:
    aberration, above, above_value, accbands, ad, adosc, adx, alma, amat, ao, aobv, apo, aroon, atr, bbands, below, below_value, bias, bop, brar, cci, cdl_pattern, cdl_z, cfo, cg, chop, cksp, cmf, cmo, coppock, cross, cross_value, cti, decay, decreasing, dema, dm, donchian, dpo, ebsw, efi, ema, entropy, eom, er, eri, fisher, fwma, ha, hilo, hl2, hlc3, hma, hwc, hwma, ichimoku, increasing, inertia, jma, kama, kc, kdj, kst, kurtosis, kvo, linreg, log_return, long_run, macd, mad, massi, mcgd, median, mfi, midpoint, midprice, mom, natr, nvi, obv, ohlc4, pdist, percent_return, pgo, ppo, psar, psl, pvi, pvo, pvol, pvr, pvt, pwma, qqe, qstick, quantile, rma, roc, rsi, rsx, rvgi, rvi, short_run, sinwma, skew, slope, sma, smi, squeeze, squeeze_pro, ssf, stc, stdev, stoch, stochrsi, supertrend, swma, t3, td_seq, tema, thermo, tos_stdevall, trima, trix, true_range, tsi, tsignals, ttm_trend, ui, uo, variance, vhf, vidya, vortex, vp, vwap, vwma, wcp, willr, wma, xsignals, zlma, zscore

Candle Patterns:
    2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods

In [ ]:
ind_list = df.ta.indicators(as_list=True)
ind_list

['aberration',
 'above',
 'above_value',
 'accbands',
 'ad',
 'adosc',
 'adx',
 'alma',
 'amat',
 'ao',
 'aobv',
 'apo',
 'aroon',
 'atr',
 'bbands',
 'below',
 'below_value',
 'bias',
 'bop',
 'brar',
 'cci',
 'cdl_pattern',
 'cdl_z',
 'cfo',
 'cg',
 'chop',
 'cksp',
 'cmf',
 'cmo',
 'coppock',
 'cross',
 'cross_value',
 'cti',
 'decay',
 'decreasing',
 'dema',
 'dm',
 'donchian',
 'dpo',
 'ebsw',
 'efi',
 'ema',
 'entropy',
 'eom',
 'er',
 'eri',
 'fisher',
 'fwma',
 'ha',
 'hilo',
 'hl2',
 'hlc3',
 'hma',
 'hwc',
 'hwma',
 'ichimoku',
 'increasing',
 'inertia',
 'jma',
 'kama',
 'kc',
 'kdj',
 'kst',
 'kurtosis',
 'kvo',
 'linreg',
 'log_return',
 'long_run',
 'macd',
 'mad',
 'massi',
 'mcgd',
 'median',
 'mfi',
 'midpoint',
 'midprice',
 'mom',
 'natr',
 'nvi',
 'obv',
 'ohlc4',
 'pdist',
 'percent_return',
 'pgo',
 'ppo',
 'psar',
 'psl',
 'pvi',
 'pvo',
 'pvol',
 'pvr',
 'pvt',
 'pwma',
 'qqe',
 'qstick',
 'quantile',
 'rma',
 'roc',
 'rsi',
 'rsx',
 'rvgi',
 'rvi',
 'short_run',
 'sinwma',
 'skew',
 'slope',
 'sma',
 'smi',
 'squeeze',
 'squeeze_pro',
 'ssf',
 'stc',
 'stdev',
 'stoch',
 'stochrsi',
 'supertrend',
 'swma',
 't3',
 'td_seq',
 'tema',
 'thermo',
 'tos_stdevall',
 'trima',
 'trix',
 'true_range',
 'tsi',
 'tsignals',
 'ttm_trend',
 'ui',
 'uo',
 'variance',
 'vhf',
 'vidya',
 'vortex',
 'vp',
 'vwap',
 'vwma',
 'wcp',
 'willr',
 'wma',
 'xsignals',
 'zlma',
 'zscore']

In [ ]:
CustomStrategy = ta.Strategy(
    name="Momo and Volatility",
    description="SMA 50,200, BBANDS, RSI, MACD and Volume SMA 20",
    ta=[
        {"kind": "sma", "length": 50},
        {"kind": "sma", "length": 200},
        {"kind": "bbands", "length": 20},
        {"kind": "rsi"},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
        ]
)
df.ta.strategy(CustomStrategy)

In [ ]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,CUMLOGRET_1,SMA_50,SMA_200,BBL_20_2.0,BBM_20_2.0,BBU_20_2.0,BBB_20_2.0,BBP_20_2.0,RSI_14,MACD_8_21_9,MACDh_8_21_9,MACDs_8_21_9,VOLUME_SMA_20
Date,,,,,,,,,,,,,,,,,,,,
2018-04-02 00:00:00-04:00,39.715360,40.263520,39.198184,39.724892,150347200,0.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-03 00:00:00-04:00,39.953691,40.218238,39.295901,40.132439,121112000,0.0,0.0,0.010207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-04 00:00:00-04:00,39.295895,40.995187,39.269678,40.899857,138422000,0.0,0.0,0.029149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-05 00:00:00-04:00,41.131031,41.524275,41.011866,41.183464,107732800,0.0,0.0,0.036059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-06 00:00:00-04:00,40.747333,41.107210,40.087157,40.130058,140021200,0.0,0.0,0.010148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-23 00:00:00-04:00,158.830002,161.550003,157.679993,158.929993,67622100,0.0,0.0,1.386486,148.248469,147.518130,143.634039,152.101000,160.567962,11.133341,0.903273,64.005749,3.112361,0.841307,2.271055,67197580.0
2023-03-24 00:00:00-04:00,158.860001,160.339996,157.850006,160.250000,59196500,0.0,0.0,1.394757,148.787739,147.579221,143.984548,152.778000,161.571452,11.511411,0.924862,65.895392,3.333091,0.849629,2.483462,67383925.0
2023-03-27 00:00:00-04:00,159.940002,160.770004,157.869995,158.279999,52390300,0.0,0.0,1.382388,149.289207,147.634195,144.487716,153.296000,162.104284,11.491864,0.782915,60.768001,3.163140,0.543742,2.619398,67753515.0
2023-03-28 00:00:00-04:00,157.970001,158.490005,155.979996,157.649994,45992200,0.0,0.0,1.378399,149.751116,147.712498,145.240634,153.807999,162.375365,11.140338,0.724223,59.182037,2.896343,0.221556,2.674787,67525775.0
2023-03-29 00:00:00-04:00,159.369995,161.050003,159.350006,160.770004,51251300,0.0,0.0,1.397997,150.251861,147.833825,146.440955,154.581000,162.721045,10.531753,0.880158,64.169383,3.058884,0.307278,2.751606,67314390.0

In [ ]:

df.ta.categories

['candles',
 'cycles',
 'momentum',
 'overlap',
 'performance',
 'statistics',
 'trend',
 'volatility',
 'volume']

In [ ]:
df.ta.strategy('Momentum')

In [ ]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,CUMLOGRET_1,SMA_50,SMA_200,...,STOCHk_14_3_3,STOCHd_14_3_3,STOCHRSIk_14_14_3_3,STOCHRSId_14_14_3_3,TRIX_30_9,TRIXs_30_9,TSI_13_25_13,TSIs_13_25_13,UO_7_14_28,WILLR_14
Date,,,,,,,,,,,,,,,,,,,,,
2018-04-02 00:00:00-04:00,39.715360,40.263520,39.198184,39.724892,150347200,0.0,0.0,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-03 00:00:00-04:00,39.953691,40.218238,39.295901,40.132439,121112000,0.0,0.0,0.010207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-04 00:00:00-04:00,39.295895,40.995187,39.269678,40.899857,138422000,0.0,0.0,0.029149,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-05 00:00:00-04:00,41.131031,41.524275,41.011866,41.183464,107732800,0.0,0.0,0.036059,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-06 00:00:00-04:00,40.747333,41.107210,40.087157,40.130058,140021200,0.0,0.0,0.010148,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-23 00:00:00-04:00,158.830002,161.550003,157.679993,158.929993,67622100,0.0,0.0,1.386486,148.248469,147.518130,...,82.677207,88.643916,88.435186,92.277773,0.154007,0.140886,20.512620,15.347195,56.465848,-22.092271
2023-03-24 00:00:00-04:00,158.860001,160.339996,157.850006,160.250000,59196500,0.0,0.0,1.394757,148.787739,147.579221,...,78.599405,83.437377,88.193676,89.729823,0.158511,0.143910,22.189959,16.324733,56.661576,-13.007567
2023-03-27 00:00:00-04:00,159.940002,160.770004,157.869995,158.279999,52390300,0.0,0.0,1.382388,149.289207,147.634195,...,79.444810,80.240474,84.852881,87.160581,0.162852,0.147223,22.138410,17.155258,49.618722,-26.565733
2023-03-28 00:00:00-04:00,157.970001,158.490005,155.979996,157.649994,45992200,0.0,0.0,1.378399,149.751116,147.712498,...,76.508359,78.184191,74.938377,82.661645,0.166842,0.150783,21.642236,17.796255,51.883354,-30.901623
2023-03-29 00:00:00-04:00,159.369995,161.050003,159.350006,160.770004,51251300,0.0,0.0,1.397997,150.251861,147.833825,...,77.701303,77.884824,71.390793,77.060684,0.171025,0.154559,22.691883,18.495630,54.194964,-9.428735

In [ ]:
resukt = ta.cagr(df['Close'])
max_draw = ta.max_drawndown(df['Close'])
sr = ta.sharpe_ratio(df['Close'])
calmar = ta.calmar_ratio(df['Close'])
sortino = ta.sortino_ratio(df['Close'])